PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX planning-ontology: <https://purl.org/ai4s/ontology/planning#>
PREFIX tp-ont: <https://w3id.org/tp-ont/ontology#>
SELECT DISTINCT ?obj WHERE {
  ?problem rdf:type planning-ontology:PlanningProblem ;
           rdfs:label "LogisticsDomain_instance-1"@en ;
           planning-ontology:hasInitialState ?state .
  ?proposition tp-ont:partOf ?state;
             tp-ont:hasFluent ?fluent ;
             tp-ont:hasArg0 ?obj ;
             tp-ont:hasArg1 ?loc .
  ?loc rdf:type tp-ont:Place ;
             rdfs:label "apt2"@en .
  ?fluent rdfs:label "at"@en .
}